### ISSUE TITLE
Implement isDeleted for Document

### ISSUE THREAD

**Issue by niklasl** [libris/whelk-core#1]
The deleted property has been removed from the Document class. All code handling deletes must have some way of setting and detecting this. The fact of deleted is currently manifested as a non-null timestamp value for the new deleted column in the postgres db (lddb).

I assume the solution is something like:
- re-add isDeleted (when deleted != null), or change checks for deleted to doc.deleted != null
- Ensure that deleted timestamps are properly set when whelk.deleteDocument (or similar) is called

**Comment by niklasl** [comment]
Did we just do this? Ping @jannistsiroyannis.

**Comment by jannistsiroyannis** [comment]
We did, but the property is called [get/set]Deleted. And it's based on the recordStatus part of the document.
